project:
  type: website

website:
  title: ""
  sidebar:
    title: "Binomial Distribution in Epidemiology"
    style: "docked"
    search: true
    collapse-level: 1
    page-navigation: true
    contents:
      
      - text: "Home"
        href: "index.qmd"
        
      
      - section: "SE01: Understanding the Binomial Distribution"
        href: "se01/index.qmd"
        
        contents:
          
          - text: "Section 1: Single Page Demonstration"
            href: "se01/binomial-demo-se01-sec01-sp01.qmd"
            
          
        
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true