module:
  code: EPM102
  title: Example Module
  description: Example description
  default_render_mode: multi_page
  id: epm102
sessions:
- code: SE01
  title: Example Session
  sections:
  - number: 1
    title: Example Section
    subpages:
    - title: Example Page
      kind: text_page
      id: epm102-se01-sec01-sp01
    id: epm102-se01-sec01
  id: epm102-se01
