project:
  type: website
  output-dir: ../output/docs

website:
  title: "Interaction Documentation"
  sidebar:
    contents:
      - section: "Interactions"
        contents:
          - interactions/index.qmd
          - interactions/tabs.qmd
          - interactions/reveal.qmd
          - interactions/quiz.qmd
          - interactions/tables.qmd

format:
  html:
    theme: cosmo
    toc: true
